import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import RQProvider from '@/app/_component/RQProvider';

import styles from './_component/main.module.css';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: '제로웰 AI 챗봇',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang='ko'>
      <body className={pretendard.className}>
        <div className={styles.container}>
          <RQProvider>{children}</RQProvider>
        </div>
      </body>
    </html>
  );
}
